spring:
  application:
    name: Str818Merchants
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/passbook?autoReconnect=true
    username: root
    password: initial123
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: passbook
      listener:
        concurrency: 4

server:
  port: 9572

logging:
  level: debug
  file: str818-merchants.log
